name: Build Latest

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - stable/**
      - .github/workflows/build-latest.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up dynamic build ARGs
        id: getargs
        run: echo "version=$(cat ./stable/VERSION)" >> $GITHUB_OUTPUT
      -
        name: Set up Docker metadata for Alpine
        id: meta-alpine
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ github.repository }}
            ghcr.io/${{ github.repository }}
          tags: |
            type=raw,latest
          labels: |
            org.opencontainers.image.vendor=The Goofball - goofball222@gmail.com
            org.opencontainers.image.title=DNS over HTTPS Server/Client
            org.opencontainers.image.description=DNS over HTTPS Server/Client
            org.opencontainers.image.version=${{ steps.getargs.outputs.version }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push Alpine Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./stable
          file: ./stable/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-alpine.outputs.tags }}
          labels: ${{ steps.meta-alpine.outputs.labels }}
          build-args: VERSION=${{ steps.getargs.outputs.version }}

